require('nvim-treesitter.configs').setup {
    -- ensure_installed = 'all',
    ensure_installed = { 'clojure',
                         'css',
                         'dockerfile',
                         'gitcommit',
                         'gitignore',
                         'help',
                         'html',
                         'javascript',
                         'json',
                         'json5',
                         'lua',
                         'make',
                         'markdown',
                         'nix',
                         'ocaml',
                         'ocaml_interface',
                         'ruby',
                         'vim',
                         'yaml'},
    sync_install = false,
    auto_install = false,
    ignore_install = {},
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = { 'org' }
    },
}
